server:
  http_port: 8080
  https_port: 8443
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_size: 1048576  # 1MB
  http2_enabled: true

log:
  level: "info"
  format: "json"