rules:
  # API routes
  - host: "localhost"
    path: "/api/v1"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "api-service"
    middleware: ["logging", "rate_limit"]
    headers:
      X-API-Version: "v1"
    timeout: 30s
    retry_policy:
      attempts: 3
      backoff: 1s

  # Web application routes
  - host: "localhost"
    path: "/"
    methods: ["GET", "POST"]
    upstream: "web-service"
    middleware: ["logging", "compression"]
    rewrite:
      strip_prefix: "/app"
    timeout: 60s

  # Static content routes
  - host: "localhost"
    path: "/static"
    methods: ["GET"]
    upstream: "static-service"
    middleware: ["logging"]
    rewrite:
      strip_prefix: "/static"
    headers:
      Cache-Control: "public, max-age=3600"
