enabled: true

autocert:
  enabled: true
  email: "admin@example.com"
  hosts:
    - "localhost"
    - "127.0.0.1"
    - "api.example.com"
    - "app.example.com"
    - "static.example.com"
  cache_dir: "./certs"
  staging: true

certificates:
  - hosts:
      - "localhost"
      - "127.0.0.1"
    auto_generate: true
    self_signed: true
    valid_for: "8760h"
    rsa_bits: 2048
    common_name: "localhost"
    organization: "Sentinel Inc."
    cert_file: "./certs/localhost-cert.pem"
    key_file: "./certs/localhost-key.pem"